### ISSUE TITLE
java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticPointFormatsExtension

### ISSUE THREAD

**Issue by wingyiu** [otrosien/demo-http2#3]
`java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticPointFormatsExtension`
what happen?

**Comment by otrosien** [comment]
could be an incompatibility between your JDK version and the jetty-alpn agent. What JDK are you using?

**Comment by otrosien** [comment]
maybe related: https://github.com/playframework/play-scala-tls-example/issues/60
